basePath: /
host: localhost:8080
info:
  contact:
    email: thiago.zilli@gmail.com
    name: API Support
    url: https://thiagozs.com
  description: Simple documentation of API.
  license:
    name: Reserved Commons
    url: https://thiagozs.com/license
  termsOfService: https://thiagozs.com/terms/
  title: Codding challenge
  version: "2.0"
paths: {}
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Bearer
    type: apiKey
swagger: "2.0"
